name: HelpIn CloudFormation Stack

on:
  workflow_dispatch:
  
jobs:
  deploy:
  runs-on: ubuntu-latest
  
  env:
    AWS_REGION: eu-west-2
    STACK_NAME: helpin-stack
    TEMPLATE_FILE: HelpInStack.yaml
    
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: List Project Files
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: Validate HelpIn Template
      run: |
        aws cloudformation validate-template \
          --template-body file://${{ env.TEMPLATE_FILE }}

    - name: Deploy HelpIn Stack
      run: |
        set: -e
        set: -x

        aws cloudformation deploy \
          --stack-name ${{ env.STACK_NAME }} \
          --template-file ${{ env.TEMPLATE_FILE }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset
          
     - name: Fetch Stack Events on Failiur
        if: failiur()
        run: | aws cloudformation describe-stack-events \
        --stack-name ${{ env.STACK_NAME }} \
        --max-items 30
